### ISSUE TITLE
Insert-size not being computed

### ISSUE THREAD

**Issue by LemoAlex** [adigenova/fastsg#3]
Dear fast-sg users,

I am trying to run a hybrid assembly using Illumina and PacBio reads. 

1) I obtained my contigs using Abyss 2.0 on an Illumina-only assembly.
2) I corrected my PacBio reads using Lordec
3) I ran : 
./FAST-SG.pl -k 30 -t 16 -l path_to_config_file -r Abyss-scaffolds.fa -p Output

My config file looks like :
long pac Path_toPacBio.fasta 500,1000,2000,4000,6000,8000,10000,12000,14000,16000,18000,20000,30000,40000,50000,60000,70000,80000,100000,120000,150000,180000 1

I have now several questions.
First, how do I choose my insert size in the config file? I used from 500 to 180k as specified in the tutorial, but how am I supposed to know what's best with my data?

Second, my log file doesn't report the insert size average (see attached)
[Anc_fastsg1.kmc.K30.log](https://github.com/adigenova/fast-sg/files/4392678/Anc_fastsg1.kmc.K30.log)
I tried to manually run the command, but I didn't achieve it.
So, how can I get my insert size average so I can use Scaffmatch?

Thanks for the help,
Alexandre

**Comment by adigenova** [comment]
Hi Alexandre,

## First, how do I choose my insert size in the config file? I used from 500 to 180k as specified in the tutorial, but how am I supposed to know what's best with my data?

The insert size is set taking into account the length of the long-reads (N50). The example that you used is for ultra-long nanopore reads. For pacbio reads, the list of insert sizes should be more like this:
```
500,1000,2000,4000,6000,8000,10000,12000,14000,16000,18000,20000,30000
```
To set the maximum size is good to compute the N90 of the reads, and set the maximum insert-size to that value.
The log that you are looking at is the log of KMC. Fast-SG print the insert-size to the standard output. So, you should run fast-sg like this:

```
./FAST-SG.pl -k 30 -t 16 -l path_to_config_file -r Abyss-scaffolds.fa -p Output > Ouput.fast-sg.log
```  

Now, we have a new hybrid assembler [Wengan](https://github.com/adigenova/wengan), which is a complete and better solution than using the fast-sg pipeline.

Best,
Alex

**Comment by LemoAlex** [comment]
Hi,

Thanks for the answer!

So basically the recommandation would be to use Wengan instead. I specifically chose Fast-SG because it worked nicely with low-coverage PacBio (5x-10x) data though. Does wengan provides the same resolution with similar data?

I quickly checked it, wengan A looks like a good option for what I'm trying to do. Can I still use the pacbio corrected reads though?

Thanks again,

Alexandre

**Comment by adigenova** [comment]
Hi, 
##  I specifically chose Fast-SG because it worked nicely with low-coverage PacBio (5x-10x) data though. Does wengan provides the same resolution with similar data?

Yes, it works well with low coverage data. Check the preprint there is a result section that explores this. 

## I quickly checked it, Wengan A looks like a good option for what I'm trying to do. Can I still use the pacbio corrected reads though?
Yes, you can use the corrected reads.  I suggest also to try the raw long-reads and the WenganD mode, which is the mode that produces the most contiguous assemblies. 
As you have low long-read coverage set the  **-N** parameter of Wengan to a low number i.e  **-N 2**, default is **-N 5**. 

Best,
Alex
